services:
  server:
    image: localhost${PWD}
    build: ./env
    volumes:
      - ./src:/mnt/docs:ro
    ports:
      - 8000:8000
    working_dir: /mnt/docs
    command: ["serve", "-a", "0.0.0.0:8000"]
